### ISSUE TITLE
Update Node version on GitHub actions

### ISSUE THREAD

**Issue by broccolinisoup** [primer/behaviors#212]
There are quite a few GitHub Actions in this repo that uses node version 16 and its support is [EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol)

GitHub Actions list that uses nodejs 16: https://github.com/search?q=repo%3Aprimer%2Fbehaviors%20node-version&type=code

We need to update these actions to use higher, possibly latest Node versions.

**Comment by broccolinisoup** [comment]
This is not specific to react but I thought adding it to the board might increase the visibility and we can chat about it in the planning session. Feel free to move it to somewhere else if it doesn't make sense here.

**Comment by lesliecdubs** [comment]
@joshblack will try to put up a quick PR to verify what breaks so we can better size this effort.

**Comment by joshblack** [comment]
Opened up a quick PR for this: https://github.com/primer/behaviors/pull/213

Seems like the workflows are good to go if we want to just give it a shot! 👍 Only ones that are still potentially breaking are the release actions but we're currently using v18 with those on other repos so I think it should be okay.
