### ISSUE TITLE
Add support for contenteditable=true in iterateFocusableElements

### ISSUE THREAD

**Issue by JelloBagel** [primer/behaviors#236]
Elements with `contenteditable=true` are focusable natively in the browser. We would like for `iterateFocusableElements` method to also account for `contenteditable` when checking for focusable elements

MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

Snippet in iterate-focusable-elements.ts where focus is checked: https://github.com/primer/behaviors/blob/main/src/utils/iterate-focusable-elements.ts#L86

**Comment by keithamus** [comment]
Thanks for the issue @JelloBagel! Would you be interested in making a PR for this?

**Comment by JelloBagel** [comment]
@keithamus sure, I can take a stab at it when I get a moment this week or the next 😃
