### ISSUE TITLE
Focus Zone, moving focus stops working upwards if hidden attribute is set to true of an element in the focus flow

### ISSUE THREAD

**Issue by 1951FDG** [primer/behaviors#257]
Moving focus stops working upwards if hidden attribute is set to true of an element in the focus flow

To reproduce:

I have button that I hide when it is clicked

Start moving focus downwards till button is reached, click that button, click handler will execute `button.hidden = true;`
moving focus downwards if further elements are present below the now hidden button works
moving focus upwards from where the button was previously displayed no longer works

So setting an element to hidden in the chain, disrupts the focus flow upwards starting from that element

**Comment by siddharthkp** [comment]
Hi! 

Thanks for taking the time to report this, do you mind creating adding a reproduction of the issue on codesandbox.io or stackblitz.com?

**Comment by 1951FDG** [comment]
Hi!

Please use same fiddle as https://github.com/primer/behaviors/issues/258

To reproduce, click the "submit" button,

- left arrow key to move focus to elements before the hidden button (will not work !)
- use right arrow key to move focus to elements after the hidden button (will work)

**Comment by lesliecdubs** [comment]
Thanks for reporting! We believe this is something that may have also been an issue in primer/view_components that was resolved by @TylerJDev. Tyler, does that sound familiar? If so, would you be willing to take a look at upstreaming that work into primer/behaviors as well?

**Comment by TylerJDev** [comment]
Yup, this does sound similar to the issue that we fixed in PVC. I'll take a look to see if we can implement the same fix here.
