### ISSUE TITLE
Focus Zone, ArrowVertical does not take into account input elements that have step defined

### ISSUE THREAD

**Issue by 1951FDG** [primer/behaviors#258]
For ArrowVertical does not take into account input elements of type "number" that have step defined, meaning it overrides the default behaviour making stepping with up and down key no longer working.

I think this can be fixable by adding some code to: https://github.com/primer/behaviors/blob/92e06b516eb3751bcf864c3678fd2722df885f4f/src/focus-zone.ts#L261

**Comment by siddharthkp** [comment]
Hi! 

Thanks for taking the time to report this, do you mind creating adding a reproduction of the issue on codesandbox.io or stackblitz.com?

**Comment by 1951FDG** [comment]
Hi!

I hope this helps, since I don't have either

https://jsfiddle.net/2j6nr01x/

**Comment by 1951FDG** [comment]
So to have stepping of the number input working again with up and down arrow key, remove FocusKeys.ArrowVertical

**Comment by lesliecdubs** [comment]
@camertron is going to take a quick look to see if we can validate this bug by looking at the test suite and we can go from there.

**Comment by camertron** [comment]
Hey @1951FDG, I'm not sure what you mean by "remove FocusKeys.ArrowVertical." However I think you were correct to identify `shouldIgnoreFocusHandling` as the place to make the change. Can you try adding the following code to the end of that function?

```typescript
if (activeElement instanceof HTMLInputElement && activeElement.type === 'number') {
  return true
}
```

**Comment by 1951FDG** [comment]
Hey @camertron, cool, I'll look into this as soon as I'm back next year, and maybe submit a pull request for it to be reviewed.

**Comment by joshblack** [comment]
Hi all! 👋 Just wanted to check-in to see if this issue is still relevant and close it, if not 👀

**Comment by 1951FDG** [comment]
Hi there, if I make the necessary changes, and submit a pull-request, will it be merged, or are these changes to be made on a per use case.

**Comment by keithamus** [comment]
PRs are always welcome, provided there is a motivating use case and the code is clean and well tested 👍
