### ISSUE TITLE
`getAnchoredPosition` returns position without perfectly aligned edges

### ISSUE THREAD

**Issue by khiga8** [primer/behaviors#63]
## Context

We use `getAnchoredPosition` for `primer-tooltip` positioning (which is soon to be upstreamed to PVC). 

In some scenarios, we observed the tooltip is not perfectly aligned at edge, particularly when there's no space for perfect edge alignment. Here is an example where `align` is `end`.

<img width="335" alt="Screenshot of tooltip edge not perfectly aligned at edge of anchor element" src="https://user-images.githubusercontent.com/16447748/156034640-450a8612-2edf-4fa4-97cb-d54e35a44bc2.png">

I was also able to recreate this issue in storybook:

<img width="816" alt="Screenshot of storybook example where floating element edge is not perfectly aligned at edge of anchor element" src="https://user-images.githubusercontent.com/16447748/156035366-0eee05a0-ee2d-4d90-9d67-533376ac5165.png">

## Expected behavior

Since there’s no space to perfectly align end, I would have expected  `anchorAlignment` to be adjusted to `start` instead. Is that not expected behavior?

For now, we're thinking of housing additional positioning logic in tooltip to address immediate issues, but this should probably be responsibility of `getAnchoredPosition`.

**Comment by siddharthkp** [comment]
Thanks Kate! Added this to the primer-react board to prioritise it!

**Comment by khiga8** [comment]
Yay @siddharthkp! Will you let me know once this has been worked on so I can remove the extra logic from tooltip code? Thank you ☺️

**Comment by siddharthkp** [comment]
Fix released in [primer/behaviors@1.1.2](https://github.com/primer/behaviors/releases/tag/v1.1.2)
