### ISSUE TITLE
Bug: when ancestor element is a wrapping `span`, `getAnchoredPosition` returns odd floating element position

### ISSUE THREAD

**Issue by khiga8** [primer/behaviors#72]
cc: @hectahertz 

When the parent container of the floating and anchor element is a `span` that wraps (and has `position: 'relative'`), `getAnchoredPosition` breaks and returns a position that is way off.

In this example, the tooltip is attached to a label, and the parent of the labels is a `span` with `position: relative`. The labels wrap:

![Screenshot of tooltip that is way on the right of the screen, and way offset from the label it is attached to](https://user-images.githubusercontent.com/16447748/159284224-a3b348f2-22f3-4997-af22-23f1a66229e7.png)

**Comment by lesliecdubs** [comment]
👋🏻 @khiga8 are you still able to replicate this bug?
